services:
  - type: web
    name: cars_rent
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: <generate with `php artisan key:generate --show`>
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <your-mysql-host>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <your-db-name>
      - key: DB_USERNAME
        value: <your-db-user>
      - key: DB_PASSWORD
        value: <your-db-password>
